#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entrega_cupones
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="prueba")]
	public partial class lts_scios_mysqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertfotos_1(fotos_1 instance);
    partial void Updatefotos_1(fotos_1 instance);
    partial void Deletefotos_1(fotos_1 instance);
    partial void Insertmaeemp_1(maeemp_1 instance);
    partial void Updatemaeemp_1(maeemp_1 instance);
    partial void Deletemaeemp_1(maeemp_1 instance);
    partial void Insertmaeflia_1(maeflia_1 instance);
    partial void Updatemaeflia_1(maeflia_1 instance);
    partial void Deletemaeflia_1(maeflia_1 instance);
    partial void Insertmaesoc_1(maesoc_1 instance);
    partial void Updatemaesoc_1(maesoc_1 instance);
    partial void Deletemaesoc_1(maesoc_1 instance);
    partial void Insertsoccen_1(soccen_1 instance);
    partial void Updatesoccen_1(soccen_1 instance);
    partial void Deletesoccen_1(soccen_1 instance);
    partial void Insertsocemp_1(socemp_1 instance);
    partial void Updatesocemp_1(socemp_1 instance);
    partial void Deletesocemp_1(socemp_1 instance);
    partial void Insertsocflia_1(socflia_1 instance);
    partial void Updatesocflia_1(socflia_1 instance);
    partial void Deletesocflia_1(socflia_1 instance);
    #endregion
		
		public lts_scios_mysqlDataContext() : 
				base(global::entrega_cupones.Properties.Settings.Default.pruebaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public lts_scios_mysqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lts_scios_mysqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lts_scios_mysqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public lts_scios_mysqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ddjj_1> ddjj_1
		{
			get
			{
				return this.GetTable<ddjj_1>();
			}
		}
		
		public System.Data.Linq.Table<ddjjt_1> ddjjt_1
		{
			get
			{
				return this.GetTable<ddjjt_1>();
			}
		}
		
		public System.Data.Linq.Table<fotos_1> fotos_1
		{
			get
			{
				return this.GetTable<fotos_1>();
			}
		}
		
		public System.Data.Linq.Table<maeemp_1> maeemp_1
		{
			get
			{
				return this.GetTable<maeemp_1>();
			}
		}
		
		public System.Data.Linq.Table<maeflia_1> maeflia_1
		{
			get
			{
				return this.GetTable<maeflia_1>();
			}
		}
		
		public System.Data.Linq.Table<maesoc_1> maesoc_1
		{
			get
			{
				return this.GetTable<maesoc_1>();
			}
		}
		
		public System.Data.Linq.Table<soccen_1> soccen_1
		{
			get
			{
				return this.GetTable<soccen_1>();
			}
		}
		
		public System.Data.Linq.Table<socemp_1> socemp_1
		{
			get
			{
				return this.GetTable<socemp_1>();
			}
		}
		
		public System.Data.Linq.Table<socflia_1> socflia_1
		{
			get
			{
				return this.GetTable<socflia_1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ddjj_1")]
	public partial class ddjj_1
	{
		
		private System.Nullable<System.DateTime> _periodo;
		
		private System.Nullable<double> _cuite;
		
		private System.Nullable<byte> _rect;
		
		private System.Nullable<double> _cuil;
		
		private System.Nullable<byte> _activo;
		
		private bool _item2;
		
		private bool _cargaf;
		
		private bool _jub;
		
		private bool _item3;
		
		private System.Nullable<double> _impo;
		
		private string _lic;
		
		private System.Nullable<double> _impoaux;
		
		private bool _item4;
		
		private bool _jorp;
		
		private System.Nullable<double> _impom1;
		
		private System.Nullable<double> _impp;
		
		private bool _item1;
		
		public ddjj_1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periodo", DbType="DateTime")]
		public System.Nullable<System.DateTime> periodo
		{
			get
			{
				return this._periodo;
			}
			set
			{
				if ((this._periodo != value))
				{
					this._periodo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuite", DbType="Float")]
		public System.Nullable<double> cuite
		{
			get
			{
				return this._cuite;
			}
			set
			{
				if ((this._cuite != value))
				{
					this._cuite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rect", DbType="TinyInt")]
		public System.Nullable<byte> rect
		{
			get
			{
				return this._rect;
			}
			set
			{
				if ((this._rect != value))
				{
					this._rect = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuil", DbType="Float")]
		public System.Nullable<double> cuil
		{
			get
			{
				return this._cuil;
			}
			set
			{
				if ((this._cuil != value))
				{
					this._cuil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="TinyInt")]
		public System.Nullable<byte> activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this._activo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item2", DbType="Bit NOT NULL")]
		public bool item2
		{
			get
			{
				return this._item2;
			}
			set
			{
				if ((this._item2 != value))
				{
					this._item2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cargaf", DbType="Bit NOT NULL")]
		public bool cargaf
		{
			get
			{
				return this._cargaf;
			}
			set
			{
				if ((this._cargaf != value))
				{
					this._cargaf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jub", DbType="Bit NOT NULL")]
		public bool jub
		{
			get
			{
				return this._jub;
			}
			set
			{
				if ((this._jub != value))
				{
					this._jub = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item3", DbType="Bit NOT NULL")]
		public bool item3
		{
			get
			{
				return this._item3;
			}
			set
			{
				if ((this._item3 != value))
				{
					this._item3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impo", DbType="Float")]
		public System.Nullable<double> impo
		{
			get
			{
				return this._impo;
			}
			set
			{
				if ((this._impo != value))
				{
					this._impo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lic", DbType="NVarChar(4)")]
		public string lic
		{
			get
			{
				return this._lic;
			}
			set
			{
				if ((this._lic != value))
				{
					this._lic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impoaux", DbType="Float")]
		public System.Nullable<double> impoaux
		{
			get
			{
				return this._impoaux;
			}
			set
			{
				if ((this._impoaux != value))
				{
					this._impoaux = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item4", DbType="Bit NOT NULL")]
		public bool item4
		{
			get
			{
				return this._item4;
			}
			set
			{
				if ((this._item4 != value))
				{
					this._item4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jorp", DbType="Bit NOT NULL")]
		public bool jorp
		{
			get
			{
				return this._jorp;
			}
			set
			{
				if ((this._jorp != value))
				{
					this._jorp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impom1", DbType="Float")]
		public System.Nullable<double> impom1
		{
			get
			{
				return this._impom1;
			}
			set
			{
				if ((this._impom1 != value))
				{
					this._impom1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impp", DbType="Float")]
		public System.Nullable<double> impp
		{
			get
			{
				return this._impp;
			}
			set
			{
				if ((this._impp != value))
				{
					this._impp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item1", DbType="Bit NOT NULL")]
		public bool item1
		{
			get
			{
				return this._item1;
			}
			set
			{
				if ((this._item1 != value))
				{
					this._item1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ddjjt_1")]
	public partial class ddjjt_1
	{
		
		private System.Nullable<System.DateTime> _periodo;
		
		private System.Nullable<double> _cuit;
		
		private System.Nullable<byte> _rect;
		
		private System.Nullable<System.DateTime> _fpres;
		
		private System.Nullable<System.DateTime> _fpago;
		
		private System.Nullable<System.DateTime> _fproc;
		
		private System.Nullable<System.DateTime> _fmod;
		
		private string _usuario;
		
		private System.Nullable<double> _titem2;
		
		private System.Nullable<double> _titem1;
		
		private System.Nullable<double> _titem3;
		
		private System.Nullable<short> _ctrlleg;
		
		private System.Nullable<double> _ctrlimp;
		
		private System.Nullable<double> _impex1;
		
		private System.Nullable<byte> _estado;
		
		private System.Nullable<System.DateTime> _fpago2;
		
		private System.Nullable<double> _impban1;
		
		private System.Nullable<double> _impban2;
		
		private System.Nullable<int> _trans1;
		
		private System.Nullable<int> _trans2;
		
		private System.Nullable<double> _titem4;
		
		private System.Nullable<double> _impex2;
		
		private System.Nullable<byte> _repite;
		
		private System.Nullable<double> _impex3;
		
		private System.Nullable<double> _impban3;
		
		private System.Nullable<System.DateTime> _fpago3;
		
		private System.Nullable<int> _trans3;
		
		private string _nver;
		
		private System.Nullable<short> _acta;
		
		private System.Nullable<byte> _medio1;
		
		private System.Nullable<byte> _medio2;
		
		private System.Nullable<byte> _medio3;
		
		public ddjjt_1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periodo", DbType="DateTime")]
		public System.Nullable<System.DateTime> periodo
		{
			get
			{
				return this._periodo;
			}
			set
			{
				if ((this._periodo != value))
				{
					this._periodo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuit", DbType="Float")]
		public System.Nullable<double> cuit
		{
			get
			{
				return this._cuit;
			}
			set
			{
				if ((this._cuit != value))
				{
					this._cuit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rect", DbType="TinyInt")]
		public System.Nullable<byte> rect
		{
			get
			{
				return this._rect;
			}
			set
			{
				if ((this._rect != value))
				{
					this._rect = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fpres", DbType="DateTime")]
		public System.Nullable<System.DateTime> fpres
		{
			get
			{
				return this._fpres;
			}
			set
			{
				if ((this._fpres != value))
				{
					this._fpres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fpago", DbType="DateTime")]
		public System.Nullable<System.DateTime> fpago
		{
			get
			{
				return this._fpago;
			}
			set
			{
				if ((this._fpago != value))
				{
					this._fpago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fproc", DbType="DateTime")]
		public System.Nullable<System.DateTime> fproc
		{
			get
			{
				return this._fproc;
			}
			set
			{
				if ((this._fproc != value))
				{
					this._fproc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fmod", DbType="DateTime")]
		public System.Nullable<System.DateTime> fmod
		{
			get
			{
				return this._fmod;
			}
			set
			{
				if ((this._fmod != value))
				{
					this._fmod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NVarChar(20)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this._usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titem2", DbType="Float")]
		public System.Nullable<double> titem2
		{
			get
			{
				return this._titem2;
			}
			set
			{
				if ((this._titem2 != value))
				{
					this._titem2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titem1", DbType="Float")]
		public System.Nullable<double> titem1
		{
			get
			{
				return this._titem1;
			}
			set
			{
				if ((this._titem1 != value))
				{
					this._titem1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titem3", DbType="Float")]
		public System.Nullable<double> titem3
		{
			get
			{
				return this._titem3;
			}
			set
			{
				if ((this._titem3 != value))
				{
					this._titem3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctrlleg", DbType="SmallInt")]
		public System.Nullable<short> ctrlleg
		{
			get
			{
				return this._ctrlleg;
			}
			set
			{
				if ((this._ctrlleg != value))
				{
					this._ctrlleg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctrlimp", DbType="Float")]
		public System.Nullable<double> ctrlimp
		{
			get
			{
				return this._ctrlimp;
			}
			set
			{
				if ((this._ctrlimp != value))
				{
					this._ctrlimp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impex1", DbType="Float")]
		public System.Nullable<double> impex1
		{
			get
			{
				return this._impex1;
			}
			set
			{
				if ((this._impex1 != value))
				{
					this._impex1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="TinyInt")]
		public System.Nullable<byte> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this._estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fpago2", DbType="DateTime")]
		public System.Nullable<System.DateTime> fpago2
		{
			get
			{
				return this._fpago2;
			}
			set
			{
				if ((this._fpago2 != value))
				{
					this._fpago2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impban1", DbType="Float")]
		public System.Nullable<double> impban1
		{
			get
			{
				return this._impban1;
			}
			set
			{
				if ((this._impban1 != value))
				{
					this._impban1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impban2", DbType="Float")]
		public System.Nullable<double> impban2
		{
			get
			{
				return this._impban2;
			}
			set
			{
				if ((this._impban2 != value))
				{
					this._impban2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trans1", DbType="Int")]
		public System.Nullable<int> trans1
		{
			get
			{
				return this._trans1;
			}
			set
			{
				if ((this._trans1 != value))
				{
					this._trans1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trans2", DbType="Int")]
		public System.Nullable<int> trans2
		{
			get
			{
				return this._trans2;
			}
			set
			{
				if ((this._trans2 != value))
				{
					this._trans2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titem4", DbType="Float")]
		public System.Nullable<double> titem4
		{
			get
			{
				return this._titem4;
			}
			set
			{
				if ((this._titem4 != value))
				{
					this._titem4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impex2", DbType="Float")]
		public System.Nullable<double> impex2
		{
			get
			{
				return this._impex2;
			}
			set
			{
				if ((this._impex2 != value))
				{
					this._impex2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repite", DbType="TinyInt")]
		public System.Nullable<byte> repite
		{
			get
			{
				return this._repite;
			}
			set
			{
				if ((this._repite != value))
				{
					this._repite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impex3", DbType="Float")]
		public System.Nullable<double> impex3
		{
			get
			{
				return this._impex3;
			}
			set
			{
				if ((this._impex3 != value))
				{
					this._impex3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impban3", DbType="Float")]
		public System.Nullable<double> impban3
		{
			get
			{
				return this._impban3;
			}
			set
			{
				if ((this._impban3 != value))
				{
					this._impban3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fpago3", DbType="DateTime")]
		public System.Nullable<System.DateTime> fpago3
		{
			get
			{
				return this._fpago3;
			}
			set
			{
				if ((this._fpago3 != value))
				{
					this._fpago3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trans3", DbType="Int")]
		public System.Nullable<int> trans3
		{
			get
			{
				return this._trans3;
			}
			set
			{
				if ((this._trans3 != value))
				{
					this._trans3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nver", DbType="NVarChar(6)")]
		public string nver
		{
			get
			{
				return this._nver;
			}
			set
			{
				if ((this._nver != value))
				{
					this._nver = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acta", DbType="SmallInt")]
		public System.Nullable<short> acta
		{
			get
			{
				return this._acta;
			}
			set
			{
				if ((this._acta != value))
				{
					this._acta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medio1", DbType="TinyInt")]
		public System.Nullable<byte> medio1
		{
			get
			{
				return this._medio1;
			}
			set
			{
				if ((this._medio1 != value))
				{
					this._medio1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medio2", DbType="TinyInt")]
		public System.Nullable<byte> medio2
		{
			get
			{
				return this._medio2;
			}
			set
			{
				if ((this._medio2 != value))
				{
					this._medio2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medio3", DbType="TinyInt")]
		public System.Nullable<byte> medio3
		{
			get
			{
				return this._medio3;
			}
			set
			{
				if ((this._medio3 != value))
				{
					this._medio3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fotos_.fotos_1")]
	public partial class fotos_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _FOTOS_CUIL;
		
		private double _FOTOS_CODFLIAR;
		
		private System.Data.Linq.Binary _FOTOS_FOTO;
		
		private System.DateTime _FOTOS_FECHA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFOTOS_CUILChanging(double value);
    partial void OnFOTOS_CUILChanged();
    partial void OnFOTOS_CODFLIARChanging(double value);
    partial void OnFOTOS_CODFLIARChanged();
    partial void OnFOTOS_FOTOChanging(System.Data.Linq.Binary value);
    partial void OnFOTOS_FOTOChanged();
    partial void OnFOTOS_FECHAChanging(System.DateTime value);
    partial void OnFOTOS_FECHAChanged();
    #endregion
		
		public fotos_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTOS_CUIL", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double FOTOS_CUIL
		{
			get
			{
				return this._FOTOS_CUIL;
			}
			set
			{
				if ((this._FOTOS_CUIL != value))
				{
					this.OnFOTOS_CUILChanging(value);
					this.SendPropertyChanging();
					this._FOTOS_CUIL = value;
					this.SendPropertyChanged("FOTOS_CUIL");
					this.OnFOTOS_CUILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTOS_CODFLIAR", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double FOTOS_CODFLIAR
		{
			get
			{
				return this._FOTOS_CODFLIAR;
			}
			set
			{
				if ((this._FOTOS_CODFLIAR != value))
				{
					this.OnFOTOS_CODFLIARChanging(value);
					this.SendPropertyChanging();
					this._FOTOS_CODFLIAR = value;
					this.SendPropertyChanged("FOTOS_CODFLIAR");
					this.OnFOTOS_CODFLIARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTOS_FOTO", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FOTOS_FOTO
		{
			get
			{
				return this._FOTOS_FOTO;
			}
			set
			{
				if ((this._FOTOS_FOTO != value))
				{
					this.OnFOTOS_FOTOChanging(value);
					this.SendPropertyChanging();
					this._FOTOS_FOTO = value;
					this.SendPropertyChanged("FOTOS_FOTO");
					this.OnFOTOS_FOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTOS_FECHA", DbType="Date NOT NULL")]
		public System.DateTime FOTOS_FECHA
		{
			get
			{
				return this._FOTOS_FECHA;
			}
			set
			{
				if ((this._FOTOS_FECHA != value))
				{
					this.OnFOTOS_FECHAChanging(value);
					this.SendPropertyChanging();
					this._FOTOS_FECHA = value;
					this.SendPropertyChanged("FOTOS_FECHA");
					this.OnFOTOS_FECHAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fotos_.maeemp_1")]
	public partial class maeemp_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _MAEEMP_CUIT;
		
		private string _MAEEMP_NOMFAN;
		
		private string _MAEEMP_RAZSOC;
		
		private string _MAEEMP_CALLE;
		
		private string _MAEEMP_NRO;
		
		private System.Nullable<char> _MAEEMP_CODPROV;
		
		private System.Nullable<long> _MAEEMP_CODLOC;
		
		private string _MAEEMP_CODPOS;
		
		private string _MAEEMP_TEL;
		
		private string _MAEEMP_EMAIL;
		
		private System.Nullable<long> _MAEEMP_CREDMAX;
		
		private System.Nullable<char> _MAEEMP_CONDCRED;
		
		private System.Nullable<byte> _MAEEMP_ACTUALIZA;
		
		private string _MAEEMP_ESTUDIO_CONTACTO;
		
		private string _MAEEMP_ESTUDIO_TEL;
		
		private string _MAEEMP_ESTUDIO_EMAIL;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAEEMP_CUITChanging(double value);
    partial void OnMAEEMP_CUITChanged();
    partial void OnMAEEMP_NOMFANChanging(string value);
    partial void OnMAEEMP_NOMFANChanged();
    partial void OnMAEEMP_RAZSOCChanging(string value);
    partial void OnMAEEMP_RAZSOCChanged();
    partial void OnMAEEMP_CALLEChanging(string value);
    partial void OnMAEEMP_CALLEChanged();
    partial void OnMAEEMP_NROChanging(string value);
    partial void OnMAEEMP_NROChanged();
    partial void OnMAEEMP_CODPROVChanging(System.Nullable<char> value);
    partial void OnMAEEMP_CODPROVChanged();
    partial void OnMAEEMP_CODLOCChanging(System.Nullable<long> value);
    partial void OnMAEEMP_CODLOCChanged();
    partial void OnMAEEMP_CODPOSChanging(string value);
    partial void OnMAEEMP_CODPOSChanged();
    partial void OnMAEEMP_TELChanging(string value);
    partial void OnMAEEMP_TELChanged();
    partial void OnMAEEMP_EMAILChanging(string value);
    partial void OnMAEEMP_EMAILChanged();
    partial void OnMAEEMP_CREDMAXChanging(System.Nullable<long> value);
    partial void OnMAEEMP_CREDMAXChanged();
    partial void OnMAEEMP_CONDCREDChanging(System.Nullable<char> value);
    partial void OnMAEEMP_CONDCREDChanged();
    partial void OnMAEEMP_ACTUALIZAChanging(System.Nullable<byte> value);
    partial void OnMAEEMP_ACTUALIZAChanged();
    partial void OnMAEEMP_ESTUDIO_CONTACTOChanging(string value);
    partial void OnMAEEMP_ESTUDIO_CONTACTOChanged();
    partial void OnMAEEMP_ESTUDIO_TELChanging(string value);
    partial void OnMAEEMP_ESTUDIO_TELChanged();
    partial void OnMAEEMP_ESTUDIO_EMAILChanging(string value);
    partial void OnMAEEMP_ESTUDIO_EMAILChanged();
    #endregion
		
		public maeemp_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CUIT", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double MAEEMP_CUIT
		{
			get
			{
				return this._MAEEMP_CUIT;
			}
			set
			{
				if ((this._MAEEMP_CUIT != value))
				{
					this.OnMAEEMP_CUITChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CUIT = value;
					this.SendPropertyChanged("MAEEMP_CUIT");
					this.OnMAEEMP_CUITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_NOMFAN", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MAEEMP_NOMFAN
		{
			get
			{
				return this._MAEEMP_NOMFAN;
			}
			set
			{
				if ((this._MAEEMP_NOMFAN != value))
				{
					this.OnMAEEMP_NOMFANChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_NOMFAN = value;
					this.SendPropertyChanged("MAEEMP_NOMFAN");
					this.OnMAEEMP_NOMFANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_RAZSOC", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MAEEMP_RAZSOC
		{
			get
			{
				return this._MAEEMP_RAZSOC;
			}
			set
			{
				if ((this._MAEEMP_RAZSOC != value))
				{
					this.OnMAEEMP_RAZSOCChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_RAZSOC = value;
					this.SendPropertyChanged("MAEEMP_RAZSOC");
					this.OnMAEEMP_RAZSOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CALLE", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MAEEMP_CALLE
		{
			get
			{
				return this._MAEEMP_CALLE;
			}
			set
			{
				if ((this._MAEEMP_CALLE != value))
				{
					this.OnMAEEMP_CALLEChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CALLE = value;
					this.SendPropertyChanged("MAEEMP_CALLE");
					this.OnMAEEMP_CALLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_NRO", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string MAEEMP_NRO
		{
			get
			{
				return this._MAEEMP_NRO;
			}
			set
			{
				if ((this._MAEEMP_NRO != value))
				{
					this.OnMAEEMP_NROChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_NRO = value;
					this.SendPropertyChanged("MAEEMP_NRO");
					this.OnMAEEMP_NROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CODPROV", DbType="Char(1)")]
		public System.Nullable<char> MAEEMP_CODPROV
		{
			get
			{
				return this._MAEEMP_CODPROV;
			}
			set
			{
				if ((this._MAEEMP_CODPROV != value))
				{
					this.OnMAEEMP_CODPROVChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CODPROV = value;
					this.SendPropertyChanged("MAEEMP_CODPROV");
					this.OnMAEEMP_CODPROVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CODLOC", DbType="BigInt")]
		public System.Nullable<long> MAEEMP_CODLOC
		{
			get
			{
				return this._MAEEMP_CODLOC;
			}
			set
			{
				if ((this._MAEEMP_CODLOC != value))
				{
					this.OnMAEEMP_CODLOCChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CODLOC = value;
					this.SendPropertyChanged("MAEEMP_CODLOC");
					this.OnMAEEMP_CODLOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CODPOS", DbType="Char(10)")]
		public string MAEEMP_CODPOS
		{
			get
			{
				return this._MAEEMP_CODPOS;
			}
			set
			{
				if ((this._MAEEMP_CODPOS != value))
				{
					this.OnMAEEMP_CODPOSChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CODPOS = value;
					this.SendPropertyChanged("MAEEMP_CODPOS");
					this.OnMAEEMP_CODPOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_TEL", DbType="Char(20)")]
		public string MAEEMP_TEL
		{
			get
			{
				return this._MAEEMP_TEL;
			}
			set
			{
				if ((this._MAEEMP_TEL != value))
				{
					this.OnMAEEMP_TELChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_TEL = value;
					this.SendPropertyChanged("MAEEMP_TEL");
					this.OnMAEEMP_TELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_EMAIL", DbType="Char(40)")]
		public string MAEEMP_EMAIL
		{
			get
			{
				return this._MAEEMP_EMAIL;
			}
			set
			{
				if ((this._MAEEMP_EMAIL != value))
				{
					this.OnMAEEMP_EMAILChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_EMAIL = value;
					this.SendPropertyChanged("MAEEMP_EMAIL");
					this.OnMAEEMP_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CREDMAX", DbType="BigInt")]
		public System.Nullable<long> MAEEMP_CREDMAX
		{
			get
			{
				return this._MAEEMP_CREDMAX;
			}
			set
			{
				if ((this._MAEEMP_CREDMAX != value))
				{
					this.OnMAEEMP_CREDMAXChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CREDMAX = value;
					this.SendPropertyChanged("MAEEMP_CREDMAX");
					this.OnMAEEMP_CREDMAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_CONDCRED", DbType="Char(1)")]
		public System.Nullable<char> MAEEMP_CONDCRED
		{
			get
			{
				return this._MAEEMP_CONDCRED;
			}
			set
			{
				if ((this._MAEEMP_CONDCRED != value))
				{
					this.OnMAEEMP_CONDCREDChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_CONDCRED = value;
					this.SendPropertyChanged("MAEEMP_CONDCRED");
					this.OnMAEEMP_CONDCREDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_ACTUALIZA", DbType="TinyInt")]
		public System.Nullable<byte> MAEEMP_ACTUALIZA
		{
			get
			{
				return this._MAEEMP_ACTUALIZA;
			}
			set
			{
				if ((this._MAEEMP_ACTUALIZA != value))
				{
					this.OnMAEEMP_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_ACTUALIZA = value;
					this.SendPropertyChanged("MAEEMP_ACTUALIZA");
					this.OnMAEEMP_ACTUALIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_ESTUDIO_CONTACTO", DbType="Char(40)")]
		public string MAEEMP_ESTUDIO_CONTACTO
		{
			get
			{
				return this._MAEEMP_ESTUDIO_CONTACTO;
			}
			set
			{
				if ((this._MAEEMP_ESTUDIO_CONTACTO != value))
				{
					this.OnMAEEMP_ESTUDIO_CONTACTOChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_ESTUDIO_CONTACTO = value;
					this.SendPropertyChanged("MAEEMP_ESTUDIO_CONTACTO");
					this.OnMAEEMP_ESTUDIO_CONTACTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_ESTUDIO_TEL", DbType="Char(20)")]
		public string MAEEMP_ESTUDIO_TEL
		{
			get
			{
				return this._MAEEMP_ESTUDIO_TEL;
			}
			set
			{
				if ((this._MAEEMP_ESTUDIO_TEL != value))
				{
					this.OnMAEEMP_ESTUDIO_TELChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_ESTUDIO_TEL = value;
					this.SendPropertyChanged("MAEEMP_ESTUDIO_TEL");
					this.OnMAEEMP_ESTUDIO_TELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEEMP_ESTUDIO_EMAIL", DbType="Char(40)")]
		public string MAEEMP_ESTUDIO_EMAIL
		{
			get
			{
				return this._MAEEMP_ESTUDIO_EMAIL;
			}
			set
			{
				if ((this._MAEEMP_ESTUDIO_EMAIL != value))
				{
					this.OnMAEEMP_ESTUDIO_EMAILChanging(value);
					this.SendPropertyChanging();
					this._MAEEMP_ESTUDIO_EMAIL = value;
					this.SendPropertyChanged("MAEEMP_ESTUDIO_EMAIL");
					this.OnMAEEMP_ESTUDIO_EMAILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fotos_.maeflia_1")]
	public partial class maeflia_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MAEFLIA_CODFLIAR;
		
		private long _MAEFLIA_NRODOC;
		
		private int _MAEFLIA_TIPODOC;
		
		private string _MAEFLIA_APELLIDO;
		
		private string _MAEFLIA_NOMBRE;
		
		private System.DateTime _MAEFLIA_FECNAC;
		
		private System.DateTime _MAEFLIA_FECING;
		
		private int _MAEFLIA_GRUSAN;
		
		private byte _MAEFLIA_RECFAR;
		
		private byte _MAEFLIA_RECCEN;
		
		private byte _MAEFLIA_RECFOC;
		
		private byte _MAEFLIA_RECFAM;
		
		private byte _MAEFLIA_RECBIB;
		
		private char _MAEFLIA_SEXO;
		
		private char _MAEFLIA_ESTCIVIL;
		
		private byte _MAEFLIA_DISCAPAC;
		
		private byte _MAEFLIA_ESTUDIA;
		
		private string _MAEFLIA_ESTABLEC;
		
		private string _MAEFLIA_AÑOESTABLEC;
		
		private string _MAEFLIA_TALLE;
		
		private string _MAEFLIA_NROCARNET;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAEFLIA_CODFLIARChanging(long value);
    partial void OnMAEFLIA_CODFLIARChanged();
    partial void OnMAEFLIA_NRODOCChanging(long value);
    partial void OnMAEFLIA_NRODOCChanged();
    partial void OnMAEFLIA_TIPODOCChanging(int value);
    partial void OnMAEFLIA_TIPODOCChanged();
    partial void OnMAEFLIA_APELLIDOChanging(string value);
    partial void OnMAEFLIA_APELLIDOChanged();
    partial void OnMAEFLIA_NOMBREChanging(string value);
    partial void OnMAEFLIA_NOMBREChanged();
    partial void OnMAEFLIA_FECNACChanging(System.DateTime value);
    partial void OnMAEFLIA_FECNACChanged();
    partial void OnMAEFLIA_FECINGChanging(System.DateTime value);
    partial void OnMAEFLIA_FECINGChanged();
    partial void OnMAEFLIA_GRUSANChanging(int value);
    partial void OnMAEFLIA_GRUSANChanged();
    partial void OnMAEFLIA_RECFARChanging(byte value);
    partial void OnMAEFLIA_RECFARChanged();
    partial void OnMAEFLIA_RECCENChanging(byte value);
    partial void OnMAEFLIA_RECCENChanged();
    partial void OnMAEFLIA_RECFOCChanging(byte value);
    partial void OnMAEFLIA_RECFOCChanged();
    partial void OnMAEFLIA_RECFAMChanging(byte value);
    partial void OnMAEFLIA_RECFAMChanged();
    partial void OnMAEFLIA_RECBIBChanging(byte value);
    partial void OnMAEFLIA_RECBIBChanged();
    partial void OnMAEFLIA_SEXOChanging(char value);
    partial void OnMAEFLIA_SEXOChanged();
    partial void OnMAEFLIA_ESTCIVILChanging(char value);
    partial void OnMAEFLIA_ESTCIVILChanged();
    partial void OnMAEFLIA_DISCAPACChanging(byte value);
    partial void OnMAEFLIA_DISCAPACChanged();
    partial void OnMAEFLIA_ESTUDIAChanging(byte value);
    partial void OnMAEFLIA_ESTUDIAChanged();
    partial void OnMAEFLIA_ESTABLECChanging(string value);
    partial void OnMAEFLIA_ESTABLECChanged();
    partial void OnMAEFLIA_AÑOESTABLECChanging(string value);
    partial void OnMAEFLIA_AÑOESTABLECChanged();
    partial void OnMAEFLIA_TALLEChanging(string value);
    partial void OnMAEFLIA_TALLEChanged();
    partial void OnMAEFLIA_NROCARNETChanging(string value);
    partial void OnMAEFLIA_NROCARNETChanged();
    #endregion
		
		public maeflia_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_CODFLIAR", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long MAEFLIA_CODFLIAR
		{
			get
			{
				return this._MAEFLIA_CODFLIAR;
			}
			set
			{
				if ((this._MAEFLIA_CODFLIAR != value))
				{
					this.OnMAEFLIA_CODFLIARChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_CODFLIAR = value;
					this.SendPropertyChanged("MAEFLIA_CODFLIAR");
					this.OnMAEFLIA_CODFLIARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_NRODOC", DbType="BigInt NOT NULL")]
		public long MAEFLIA_NRODOC
		{
			get
			{
				return this._MAEFLIA_NRODOC;
			}
			set
			{
				if ((this._MAEFLIA_NRODOC != value))
				{
					this.OnMAEFLIA_NRODOCChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_NRODOC = value;
					this.SendPropertyChanged("MAEFLIA_NRODOC");
					this.OnMAEFLIA_NRODOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_TIPODOC", DbType="Int NOT NULL")]
		public int MAEFLIA_TIPODOC
		{
			get
			{
				return this._MAEFLIA_TIPODOC;
			}
			set
			{
				if ((this._MAEFLIA_TIPODOC != value))
				{
					this.OnMAEFLIA_TIPODOCChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_TIPODOC = value;
					this.SendPropertyChanged("MAEFLIA_TIPODOC");
					this.OnMAEFLIA_TIPODOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_APELLIDO", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string MAEFLIA_APELLIDO
		{
			get
			{
				return this._MAEFLIA_APELLIDO;
			}
			set
			{
				if ((this._MAEFLIA_APELLIDO != value))
				{
					this.OnMAEFLIA_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_APELLIDO = value;
					this.SendPropertyChanged("MAEFLIA_APELLIDO");
					this.OnMAEFLIA_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_NOMBRE", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string MAEFLIA_NOMBRE
		{
			get
			{
				return this._MAEFLIA_NOMBRE;
			}
			set
			{
				if ((this._MAEFLIA_NOMBRE != value))
				{
					this.OnMAEFLIA_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_NOMBRE = value;
					this.SendPropertyChanged("MAEFLIA_NOMBRE");
					this.OnMAEFLIA_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_FECNAC", DbType="Date NOT NULL")]
		public System.DateTime MAEFLIA_FECNAC
		{
			get
			{
				return this._MAEFLIA_FECNAC;
			}
			set
			{
				if ((this._MAEFLIA_FECNAC != value))
				{
					this.OnMAEFLIA_FECNACChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_FECNAC = value;
					this.SendPropertyChanged("MAEFLIA_FECNAC");
					this.OnMAEFLIA_FECNACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_FECING", DbType="Date NOT NULL")]
		public System.DateTime MAEFLIA_FECING
		{
			get
			{
				return this._MAEFLIA_FECING;
			}
			set
			{
				if ((this._MAEFLIA_FECING != value))
				{
					this.OnMAEFLIA_FECINGChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_FECING = value;
					this.SendPropertyChanged("MAEFLIA_FECING");
					this.OnMAEFLIA_FECINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_GRUSAN", DbType="Int NOT NULL")]
		public int MAEFLIA_GRUSAN
		{
			get
			{
				return this._MAEFLIA_GRUSAN;
			}
			set
			{
				if ((this._MAEFLIA_GRUSAN != value))
				{
					this.OnMAEFLIA_GRUSANChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_GRUSAN = value;
					this.SendPropertyChanged("MAEFLIA_GRUSAN");
					this.OnMAEFLIA_GRUSANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_RECFAR", DbType="TinyInt NOT NULL")]
		public byte MAEFLIA_RECFAR
		{
			get
			{
				return this._MAEFLIA_RECFAR;
			}
			set
			{
				if ((this._MAEFLIA_RECFAR != value))
				{
					this.OnMAEFLIA_RECFARChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_RECFAR = value;
					this.SendPropertyChanged("MAEFLIA_RECFAR");
					this.OnMAEFLIA_RECFARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_RECCEN", DbType="TinyInt NOT NULL")]
		public byte MAEFLIA_RECCEN
		{
			get
			{
				return this._MAEFLIA_RECCEN;
			}
			set
			{
				if ((this._MAEFLIA_RECCEN != value))
				{
					this.OnMAEFLIA_RECCENChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_RECCEN = value;
					this.SendPropertyChanged("MAEFLIA_RECCEN");
					this.OnMAEFLIA_RECCENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_RECFOC", DbType="TinyInt NOT NULL")]
		public byte MAEFLIA_RECFOC
		{
			get
			{
				return this._MAEFLIA_RECFOC;
			}
			set
			{
				if ((this._MAEFLIA_RECFOC != value))
				{
					this.OnMAEFLIA_RECFOCChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_RECFOC = value;
					this.SendPropertyChanged("MAEFLIA_RECFOC");
					this.OnMAEFLIA_RECFOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_RECFAM", DbType="TinyInt NOT NULL")]
		public byte MAEFLIA_RECFAM
		{
			get
			{
				return this._MAEFLIA_RECFAM;
			}
			set
			{
				if ((this._MAEFLIA_RECFAM != value))
				{
					this.OnMAEFLIA_RECFAMChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_RECFAM = value;
					this.SendPropertyChanged("MAEFLIA_RECFAM");
					this.OnMAEFLIA_RECFAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_RECBIB", DbType="TinyInt NOT NULL")]
		public byte MAEFLIA_RECBIB
		{
			get
			{
				return this._MAEFLIA_RECBIB;
			}
			set
			{
				if ((this._MAEFLIA_RECBIB != value))
				{
					this.OnMAEFLIA_RECBIBChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_RECBIB = value;
					this.SendPropertyChanged("MAEFLIA_RECBIB");
					this.OnMAEFLIA_RECBIBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_SEXO", DbType="Char(1) NOT NULL")]
		public char MAEFLIA_SEXO
		{
			get
			{
				return this._MAEFLIA_SEXO;
			}
			set
			{
				if ((this._MAEFLIA_SEXO != value))
				{
					this.OnMAEFLIA_SEXOChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_SEXO = value;
					this.SendPropertyChanged("MAEFLIA_SEXO");
					this.OnMAEFLIA_SEXOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_ESTCIVIL", DbType="Char(1) NOT NULL")]
		public char MAEFLIA_ESTCIVIL
		{
			get
			{
				return this._MAEFLIA_ESTCIVIL;
			}
			set
			{
				if ((this._MAEFLIA_ESTCIVIL != value))
				{
					this.OnMAEFLIA_ESTCIVILChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_ESTCIVIL = value;
					this.SendPropertyChanged("MAEFLIA_ESTCIVIL");
					this.OnMAEFLIA_ESTCIVILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_DISCAPAC", DbType="TinyInt NOT NULL")]
		public byte MAEFLIA_DISCAPAC
		{
			get
			{
				return this._MAEFLIA_DISCAPAC;
			}
			set
			{
				if ((this._MAEFLIA_DISCAPAC != value))
				{
					this.OnMAEFLIA_DISCAPACChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_DISCAPAC = value;
					this.SendPropertyChanged("MAEFLIA_DISCAPAC");
					this.OnMAEFLIA_DISCAPACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_ESTUDIA", DbType="TinyInt NOT NULL")]
		public byte MAEFLIA_ESTUDIA
		{
			get
			{
				return this._MAEFLIA_ESTUDIA;
			}
			set
			{
				if ((this._MAEFLIA_ESTUDIA != value))
				{
					this.OnMAEFLIA_ESTUDIAChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_ESTUDIA = value;
					this.SendPropertyChanged("MAEFLIA_ESTUDIA");
					this.OnMAEFLIA_ESTUDIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_ESTABLEC", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string MAEFLIA_ESTABLEC
		{
			get
			{
				return this._MAEFLIA_ESTABLEC;
			}
			set
			{
				if ((this._MAEFLIA_ESTABLEC != value))
				{
					this.OnMAEFLIA_ESTABLECChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_ESTABLEC = value;
					this.SendPropertyChanged("MAEFLIA_ESTABLEC");
					this.OnMAEFLIA_ESTABLECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_AÑOESTABLEC", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAEFLIA_AÑOESTABLEC
		{
			get
			{
				return this._MAEFLIA_AÑOESTABLEC;
			}
			set
			{
				if ((this._MAEFLIA_AÑOESTABLEC != value))
				{
					this.OnMAEFLIA_AÑOESTABLECChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_AÑOESTABLEC = value;
					this.SendPropertyChanged("MAEFLIA_AÑOESTABLEC");
					this.OnMAEFLIA_AÑOESTABLECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_TALLE", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAEFLIA_TALLE
		{
			get
			{
				return this._MAEFLIA_TALLE;
			}
			set
			{
				if ((this._MAEFLIA_TALLE != value))
				{
					this.OnMAEFLIA_TALLEChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_TALLE = value;
					this.SendPropertyChanged("MAEFLIA_TALLE");
					this.OnMAEFLIA_TALLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAEFLIA_NROCARNET", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string MAEFLIA_NROCARNET
		{
			get
			{
				return this._MAEFLIA_NROCARNET;
			}
			set
			{
				if ((this._MAEFLIA_NROCARNET != value))
				{
					this.OnMAEFLIA_NROCARNETChanging(value);
					this.SendPropertyChanging();
					this._MAEFLIA_NROCARNET = value;
					this.SendPropertyChanged("MAEFLIA_NROCARNET");
					this.OnMAEFLIA_NROCARNETChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fotos_.maesoc_1")]
	public partial class maesoc_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _MAESOC_CUIL;
		
		private string _MAESOC_APELLIDO;
		
		private string _MAESOC_NOMBRE;
		
		private string _MAESOC_TEL;
		
		private string _MAESOC_TELCEL;
		
		private System.DateTime _MAESOC_FECHANAC;
		
		private short _MAESOC_CARGAFLIA;
		
		private int _MAESOC_JUBIL;
		
		private System.Nullable<byte> _MAESOC_PREDOC;
		
		private System.DateTime _MAESOC_FECHADOC;
		
		private short _MAESOC_CODCAT;
		
		private short _MAESOC_CODACT;
		
		private int _MAESOC_TIPODOC;
		
		private string _MAESOC_NRODOC;
		
		private int _MAESOC_GRUPOSANG;
		
		private char _MAESOC_SEXO;
		
		private char _MAESOC_ESTCIV;
		
		private char _MAESOC_CODPROV;
		
		private int _MAESOC_CODLOC;
		
		private string _MAESOC_CODPOS;
		
		private string _MAESOC_BARRIO;
		
		private string _MAESOC_NACIONALIDAD;
		
		private string _MAESOC_CALLE;
		
		private string _MAESOC_NROCALLE;
		
		private string _MAESOC_PISO;
		
		private string _MAESOC_DTO;
		
		private int _MAESOC_CODOSM;
		
		private System.Nullable<int> _MAESOC_CODCON;
		
		private string _MAESOC_NROAFIL;
		
		private string _MAESOC_EMAIL;
		
		private string _MAESOC_EMAILLAB;
		
		private string _MAESOC_NROCARNET;
		
		private string _MAESOC_IMPEST1;
		
		private string _MAESOC_IMPEST2;
		
		private string _MAESOC_IMPEST3;
		
		private string _MAESOC_IMPEST4;
		
		private string _MAESOC_IMPEST5;
		
		private string _MAESOC_IMPEST6;
		
		private string _MAESOC_DEBAUT_CBU;
		
		private double _MAESOC_DEBAUT_MONTO;
		
		private System.Nullable<byte> _MAESOC_ACTUALIZA;
		
		private System.Nullable<int> _MAESOC_DTOFARMACIA;
		
		private System.DateTime _MAESOC_FECHAALTA;
		
		private System.DateTime _MAESOC_FECHAMOD;
		
		private string _MAESOC_USUMOD;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAESOC_CUILChanging(double value);
    partial void OnMAESOC_CUILChanged();
    partial void OnMAESOC_APELLIDOChanging(string value);
    partial void OnMAESOC_APELLIDOChanged();
    partial void OnMAESOC_NOMBREChanging(string value);
    partial void OnMAESOC_NOMBREChanged();
    partial void OnMAESOC_TELChanging(string value);
    partial void OnMAESOC_TELChanged();
    partial void OnMAESOC_TELCELChanging(string value);
    partial void OnMAESOC_TELCELChanged();
    partial void OnMAESOC_FECHANACChanging(System.DateTime value);
    partial void OnMAESOC_FECHANACChanged();
    partial void OnMAESOC_CARGAFLIAChanging(short value);
    partial void OnMAESOC_CARGAFLIAChanged();
    partial void OnMAESOC_JUBILChanging(int value);
    partial void OnMAESOC_JUBILChanged();
    partial void OnMAESOC_PREDOCChanging(System.Nullable<byte> value);
    partial void OnMAESOC_PREDOCChanged();
    partial void OnMAESOC_FECHADOCChanging(System.DateTime value);
    partial void OnMAESOC_FECHADOCChanged();
    partial void OnMAESOC_CODCATChanging(short value);
    partial void OnMAESOC_CODCATChanged();
    partial void OnMAESOC_CODACTChanging(short value);
    partial void OnMAESOC_CODACTChanged();
    partial void OnMAESOC_TIPODOCChanging(int value);
    partial void OnMAESOC_TIPODOCChanged();
    partial void OnMAESOC_NRODOCChanging(string value);
    partial void OnMAESOC_NRODOCChanged();
    partial void OnMAESOC_GRUPOSANGChanging(int value);
    partial void OnMAESOC_GRUPOSANGChanged();
    partial void OnMAESOC_SEXOChanging(char value);
    partial void OnMAESOC_SEXOChanged();
    partial void OnMAESOC_ESTCIVChanging(char value);
    partial void OnMAESOC_ESTCIVChanged();
    partial void OnMAESOC_CODPROVChanging(char value);
    partial void OnMAESOC_CODPROVChanged();
    partial void OnMAESOC_CODLOCChanging(int value);
    partial void OnMAESOC_CODLOCChanged();
    partial void OnMAESOC_CODPOSChanging(string value);
    partial void OnMAESOC_CODPOSChanged();
    partial void OnMAESOC_BARRIOChanging(string value);
    partial void OnMAESOC_BARRIOChanged();
    partial void OnMAESOC_NACIONALIDADChanging(string value);
    partial void OnMAESOC_NACIONALIDADChanged();
    partial void OnMAESOC_CALLEChanging(string value);
    partial void OnMAESOC_CALLEChanged();
    partial void OnMAESOC_NROCALLEChanging(string value);
    partial void OnMAESOC_NROCALLEChanged();
    partial void OnMAESOC_PISOChanging(string value);
    partial void OnMAESOC_PISOChanged();
    partial void OnMAESOC_DTOChanging(string value);
    partial void OnMAESOC_DTOChanged();
    partial void OnMAESOC_CODOSMChanging(int value);
    partial void OnMAESOC_CODOSMChanged();
    partial void OnMAESOC_CODCONChanging(System.Nullable<int> value);
    partial void OnMAESOC_CODCONChanged();
    partial void OnMAESOC_NROAFILChanging(string value);
    partial void OnMAESOC_NROAFILChanged();
    partial void OnMAESOC_EMAILChanging(string value);
    partial void OnMAESOC_EMAILChanged();
    partial void OnMAESOC_EMAILLABChanging(string value);
    partial void OnMAESOC_EMAILLABChanged();
    partial void OnMAESOC_NROCARNETChanging(string value);
    partial void OnMAESOC_NROCARNETChanged();
    partial void OnMAESOC_IMPEST1Changing(string value);
    partial void OnMAESOC_IMPEST1Changed();
    partial void OnMAESOC_IMPEST2Changing(string value);
    partial void OnMAESOC_IMPEST2Changed();
    partial void OnMAESOC_IMPEST3Changing(string value);
    partial void OnMAESOC_IMPEST3Changed();
    partial void OnMAESOC_IMPEST4Changing(string value);
    partial void OnMAESOC_IMPEST4Changed();
    partial void OnMAESOC_IMPEST5Changing(string value);
    partial void OnMAESOC_IMPEST5Changed();
    partial void OnMAESOC_IMPEST6Changing(string value);
    partial void OnMAESOC_IMPEST6Changed();
    partial void OnMAESOC_DEBAUT_CBUChanging(string value);
    partial void OnMAESOC_DEBAUT_CBUChanged();
    partial void OnMAESOC_DEBAUT_MONTOChanging(double value);
    partial void OnMAESOC_DEBAUT_MONTOChanged();
    partial void OnMAESOC_ACTUALIZAChanging(System.Nullable<byte> value);
    partial void OnMAESOC_ACTUALIZAChanged();
    partial void OnMAESOC_DTOFARMACIAChanging(System.Nullable<int> value);
    partial void OnMAESOC_DTOFARMACIAChanged();
    partial void OnMAESOC_FECHAALTAChanging(System.DateTime value);
    partial void OnMAESOC_FECHAALTAChanged();
    partial void OnMAESOC_FECHAMODChanging(System.DateTime value);
    partial void OnMAESOC_FECHAMODChanged();
    partial void OnMAESOC_USUMODChanging(string value);
    partial void OnMAESOC_USUMODChanged();
    #endregion
		
		public maesoc_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CUIL", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double MAESOC_CUIL
		{
			get
			{
				return this._MAESOC_CUIL;
			}
			set
			{
				if ((this._MAESOC_CUIL != value))
				{
					this.OnMAESOC_CUILChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CUIL = value;
					this.SendPropertyChanged("MAESOC_CUIL");
					this.OnMAESOC_CUILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_APELLIDO", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string MAESOC_APELLIDO
		{
			get
			{
				return this._MAESOC_APELLIDO;
			}
			set
			{
				if ((this._MAESOC_APELLIDO != value))
				{
					this.OnMAESOC_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_APELLIDO = value;
					this.SendPropertyChanged("MAESOC_APELLIDO");
					this.OnMAESOC_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NOMBRE", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string MAESOC_NOMBRE
		{
			get
			{
				return this._MAESOC_NOMBRE;
			}
			set
			{
				if ((this._MAESOC_NOMBRE != value))
				{
					this.OnMAESOC_NOMBREChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NOMBRE = value;
					this.SendPropertyChanged("MAESOC_NOMBRE");
					this.OnMAESOC_NOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_TEL", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string MAESOC_TEL
		{
			get
			{
				return this._MAESOC_TEL;
			}
			set
			{
				if ((this._MAESOC_TEL != value))
				{
					this.OnMAESOC_TELChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_TEL = value;
					this.SendPropertyChanged("MAESOC_TEL");
					this.OnMAESOC_TELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_TELCEL", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string MAESOC_TELCEL
		{
			get
			{
				return this._MAESOC_TELCEL;
			}
			set
			{
				if ((this._MAESOC_TELCEL != value))
				{
					this.OnMAESOC_TELCELChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_TELCEL = value;
					this.SendPropertyChanged("MAESOC_TELCEL");
					this.OnMAESOC_TELCELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_FECHANAC", DbType="Date NOT NULL")]
		public System.DateTime MAESOC_FECHANAC
		{
			get
			{
				return this._MAESOC_FECHANAC;
			}
			set
			{
				if ((this._MAESOC_FECHANAC != value))
				{
					this.OnMAESOC_FECHANACChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_FECHANAC = value;
					this.SendPropertyChanged("MAESOC_FECHANAC");
					this.OnMAESOC_FECHANACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CARGAFLIA", DbType="SmallInt NOT NULL")]
		public short MAESOC_CARGAFLIA
		{
			get
			{
				return this._MAESOC_CARGAFLIA;
			}
			set
			{
				if ((this._MAESOC_CARGAFLIA != value))
				{
					this.OnMAESOC_CARGAFLIAChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CARGAFLIA = value;
					this.SendPropertyChanged("MAESOC_CARGAFLIA");
					this.OnMAESOC_CARGAFLIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_JUBIL", DbType="Int NOT NULL")]
		public int MAESOC_JUBIL
		{
			get
			{
				return this._MAESOC_JUBIL;
			}
			set
			{
				if ((this._MAESOC_JUBIL != value))
				{
					this.OnMAESOC_JUBILChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_JUBIL = value;
					this.SendPropertyChanged("MAESOC_JUBIL");
					this.OnMAESOC_JUBILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_PREDOC", DbType="TinyInt")]
		public System.Nullable<byte> MAESOC_PREDOC
		{
			get
			{
				return this._MAESOC_PREDOC;
			}
			set
			{
				if ((this._MAESOC_PREDOC != value))
				{
					this.OnMAESOC_PREDOCChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_PREDOC = value;
					this.SendPropertyChanged("MAESOC_PREDOC");
					this.OnMAESOC_PREDOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_FECHADOC", DbType="Date NOT NULL")]
		public System.DateTime MAESOC_FECHADOC
		{
			get
			{
				return this._MAESOC_FECHADOC;
			}
			set
			{
				if ((this._MAESOC_FECHADOC != value))
				{
					this.OnMAESOC_FECHADOCChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_FECHADOC = value;
					this.SendPropertyChanged("MAESOC_FECHADOC");
					this.OnMAESOC_FECHADOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODCAT", DbType="SmallInt NOT NULL")]
		public short MAESOC_CODCAT
		{
			get
			{
				return this._MAESOC_CODCAT;
			}
			set
			{
				if ((this._MAESOC_CODCAT != value))
				{
					this.OnMAESOC_CODCATChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODCAT = value;
					this.SendPropertyChanged("MAESOC_CODCAT");
					this.OnMAESOC_CODCATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODACT", DbType="SmallInt NOT NULL")]
		public short MAESOC_CODACT
		{
			get
			{
				return this._MAESOC_CODACT;
			}
			set
			{
				if ((this._MAESOC_CODACT != value))
				{
					this.OnMAESOC_CODACTChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODACT = value;
					this.SendPropertyChanged("MAESOC_CODACT");
					this.OnMAESOC_CODACTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_TIPODOC", DbType="Int NOT NULL")]
		public int MAESOC_TIPODOC
		{
			get
			{
				return this._MAESOC_TIPODOC;
			}
			set
			{
				if ((this._MAESOC_TIPODOC != value))
				{
					this.OnMAESOC_TIPODOCChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_TIPODOC = value;
					this.SendPropertyChanged("MAESOC_TIPODOC");
					this.OnMAESOC_TIPODOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NRODOC", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string MAESOC_NRODOC
		{
			get
			{
				return this._MAESOC_NRODOC;
			}
			set
			{
				if ((this._MAESOC_NRODOC != value))
				{
					this.OnMAESOC_NRODOCChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NRODOC = value;
					this.SendPropertyChanged("MAESOC_NRODOC");
					this.OnMAESOC_NRODOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_GRUPOSANG", DbType="Int NOT NULL")]
		public int MAESOC_GRUPOSANG
		{
			get
			{
				return this._MAESOC_GRUPOSANG;
			}
			set
			{
				if ((this._MAESOC_GRUPOSANG != value))
				{
					this.OnMAESOC_GRUPOSANGChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_GRUPOSANG = value;
					this.SendPropertyChanged("MAESOC_GRUPOSANG");
					this.OnMAESOC_GRUPOSANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_SEXO", DbType="Char(1) NOT NULL")]
		public char MAESOC_SEXO
		{
			get
			{
				return this._MAESOC_SEXO;
			}
			set
			{
				if ((this._MAESOC_SEXO != value))
				{
					this.OnMAESOC_SEXOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_SEXO = value;
					this.SendPropertyChanged("MAESOC_SEXO");
					this.OnMAESOC_SEXOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_ESTCIV", DbType="Char(1) NOT NULL")]
		public char MAESOC_ESTCIV
		{
			get
			{
				return this._MAESOC_ESTCIV;
			}
			set
			{
				if ((this._MAESOC_ESTCIV != value))
				{
					this.OnMAESOC_ESTCIVChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_ESTCIV = value;
					this.SendPropertyChanged("MAESOC_ESTCIV");
					this.OnMAESOC_ESTCIVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODPROV", DbType="Char(1) NOT NULL")]
		public char MAESOC_CODPROV
		{
			get
			{
				return this._MAESOC_CODPROV;
			}
			set
			{
				if ((this._MAESOC_CODPROV != value))
				{
					this.OnMAESOC_CODPROVChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODPROV = value;
					this.SendPropertyChanged("MAESOC_CODPROV");
					this.OnMAESOC_CODPROVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODLOC", DbType="Int NOT NULL")]
		public int MAESOC_CODLOC
		{
			get
			{
				return this._MAESOC_CODLOC;
			}
			set
			{
				if ((this._MAESOC_CODLOC != value))
				{
					this.OnMAESOC_CODLOCChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODLOC = value;
					this.SendPropertyChanged("MAESOC_CODLOC");
					this.OnMAESOC_CODLOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODPOS", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAESOC_CODPOS
		{
			get
			{
				return this._MAESOC_CODPOS;
			}
			set
			{
				if ((this._MAESOC_CODPOS != value))
				{
					this.OnMAESOC_CODPOSChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODPOS = value;
					this.SendPropertyChanged("MAESOC_CODPOS");
					this.OnMAESOC_CODPOSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_BARRIO", DbType="Char(30)")]
		public string MAESOC_BARRIO
		{
			get
			{
				return this._MAESOC_BARRIO;
			}
			set
			{
				if ((this._MAESOC_BARRIO != value))
				{
					this.OnMAESOC_BARRIOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_BARRIO = value;
					this.SendPropertyChanged("MAESOC_BARRIO");
					this.OnMAESOC_BARRIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NACIONALIDAD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAESOC_NACIONALIDAD
		{
			get
			{
				return this._MAESOC_NACIONALIDAD;
			}
			set
			{
				if ((this._MAESOC_NACIONALIDAD != value))
				{
					this.OnMAESOC_NACIONALIDADChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NACIONALIDAD = value;
					this.SendPropertyChanged("MAESOC_NACIONALIDAD");
					this.OnMAESOC_NACIONALIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CALLE", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string MAESOC_CALLE
		{
			get
			{
				return this._MAESOC_CALLE;
			}
			set
			{
				if ((this._MAESOC_CALLE != value))
				{
					this.OnMAESOC_CALLEChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CALLE = value;
					this.SendPropertyChanged("MAESOC_CALLE");
					this.OnMAESOC_CALLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NROCALLE", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MAESOC_NROCALLE
		{
			get
			{
				return this._MAESOC_NROCALLE;
			}
			set
			{
				if ((this._MAESOC_NROCALLE != value))
				{
					this.OnMAESOC_NROCALLEChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NROCALLE = value;
					this.SendPropertyChanged("MAESOC_NROCALLE");
					this.OnMAESOC_NROCALLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_PISO", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAESOC_PISO
		{
			get
			{
				return this._MAESOC_PISO;
			}
			set
			{
				if ((this._MAESOC_PISO != value))
				{
					this.OnMAESOC_PISOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_PISO = value;
					this.SendPropertyChanged("MAESOC_PISO");
					this.OnMAESOC_PISOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_DTO", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAESOC_DTO
		{
			get
			{
				return this._MAESOC_DTO;
			}
			set
			{
				if ((this._MAESOC_DTO != value))
				{
					this.OnMAESOC_DTOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_DTO = value;
					this.SendPropertyChanged("MAESOC_DTO");
					this.OnMAESOC_DTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODOSM", DbType="Int NOT NULL")]
		public int MAESOC_CODOSM
		{
			get
			{
				return this._MAESOC_CODOSM;
			}
			set
			{
				if ((this._MAESOC_CODOSM != value))
				{
					this.OnMAESOC_CODOSMChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODOSM = value;
					this.SendPropertyChanged("MAESOC_CODOSM");
					this.OnMAESOC_CODOSMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_CODCON", DbType="Int")]
		public System.Nullable<int> MAESOC_CODCON
		{
			get
			{
				return this._MAESOC_CODCON;
			}
			set
			{
				if ((this._MAESOC_CODCON != value))
				{
					this.OnMAESOC_CODCONChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_CODCON = value;
					this.SendPropertyChanged("MAESOC_CODCON");
					this.OnMAESOC_CODCONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NROAFIL", DbType="Char(15) NOT NULL", CanBeNull=false)]
		public string MAESOC_NROAFIL
		{
			get
			{
				return this._MAESOC_NROAFIL;
			}
			set
			{
				if ((this._MAESOC_NROAFIL != value))
				{
					this.OnMAESOC_NROAFILChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NROAFIL = value;
					this.SendPropertyChanged("MAESOC_NROAFIL");
					this.OnMAESOC_NROAFILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_EMAIL", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MAESOC_EMAIL
		{
			get
			{
				return this._MAESOC_EMAIL;
			}
			set
			{
				if ((this._MAESOC_EMAIL != value))
				{
					this.OnMAESOC_EMAILChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_EMAIL = value;
					this.SendPropertyChanged("MAESOC_EMAIL");
					this.OnMAESOC_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_EMAILLAB", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MAESOC_EMAILLAB
		{
			get
			{
				return this._MAESOC_EMAILLAB;
			}
			set
			{
				if ((this._MAESOC_EMAILLAB != value))
				{
					this.OnMAESOC_EMAILLABChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_EMAILLAB = value;
					this.SendPropertyChanged("MAESOC_EMAILLAB");
					this.OnMAESOC_EMAILLABChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_NROCARNET", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string MAESOC_NROCARNET
		{
			get
			{
				return this._MAESOC_NROCARNET;
			}
			set
			{
				if ((this._MAESOC_NROCARNET != value))
				{
					this.OnMAESOC_NROCARNETChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_NROCARNET = value;
					this.SendPropertyChanged("MAESOC_NROCARNET");
					this.OnMAESOC_NROCARNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST1", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST1
		{
			get
			{
				return this._MAESOC_IMPEST1;
			}
			set
			{
				if ((this._MAESOC_IMPEST1 != value))
				{
					this.OnMAESOC_IMPEST1Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST1 = value;
					this.SendPropertyChanged("MAESOC_IMPEST1");
					this.OnMAESOC_IMPEST1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST2", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST2
		{
			get
			{
				return this._MAESOC_IMPEST2;
			}
			set
			{
				if ((this._MAESOC_IMPEST2 != value))
				{
					this.OnMAESOC_IMPEST2Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST2 = value;
					this.SendPropertyChanged("MAESOC_IMPEST2");
					this.OnMAESOC_IMPEST2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST3", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST3
		{
			get
			{
				return this._MAESOC_IMPEST3;
			}
			set
			{
				if ((this._MAESOC_IMPEST3 != value))
				{
					this.OnMAESOC_IMPEST3Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST3 = value;
					this.SendPropertyChanged("MAESOC_IMPEST3");
					this.OnMAESOC_IMPEST3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST4", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST4
		{
			get
			{
				return this._MAESOC_IMPEST4;
			}
			set
			{
				if ((this._MAESOC_IMPEST4 != value))
				{
					this.OnMAESOC_IMPEST4Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST4 = value;
					this.SendPropertyChanged("MAESOC_IMPEST4");
					this.OnMAESOC_IMPEST4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST5", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST5
		{
			get
			{
				return this._MAESOC_IMPEST5;
			}
			set
			{
				if ((this._MAESOC_IMPEST5 != value))
				{
					this.OnMAESOC_IMPEST5Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST5 = value;
					this.SendPropertyChanged("MAESOC_IMPEST5");
					this.OnMAESOC_IMPEST5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_IMPEST6", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MAESOC_IMPEST6
		{
			get
			{
				return this._MAESOC_IMPEST6;
			}
			set
			{
				if ((this._MAESOC_IMPEST6 != value))
				{
					this.OnMAESOC_IMPEST6Changing(value);
					this.SendPropertyChanging();
					this._MAESOC_IMPEST6 = value;
					this.SendPropertyChanged("MAESOC_IMPEST6");
					this.OnMAESOC_IMPEST6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_DEBAUT_CBU", DbType="Char(22) NOT NULL", CanBeNull=false)]
		public string MAESOC_DEBAUT_CBU
		{
			get
			{
				return this._MAESOC_DEBAUT_CBU;
			}
			set
			{
				if ((this._MAESOC_DEBAUT_CBU != value))
				{
					this.OnMAESOC_DEBAUT_CBUChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_DEBAUT_CBU = value;
					this.SendPropertyChanged("MAESOC_DEBAUT_CBU");
					this.OnMAESOC_DEBAUT_CBUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_DEBAUT_MONTO", DbType="Float NOT NULL")]
		public double MAESOC_DEBAUT_MONTO
		{
			get
			{
				return this._MAESOC_DEBAUT_MONTO;
			}
			set
			{
				if ((this._MAESOC_DEBAUT_MONTO != value))
				{
					this.OnMAESOC_DEBAUT_MONTOChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_DEBAUT_MONTO = value;
					this.SendPropertyChanged("MAESOC_DEBAUT_MONTO");
					this.OnMAESOC_DEBAUT_MONTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_ACTUALIZA", DbType="TinyInt")]
		public System.Nullable<byte> MAESOC_ACTUALIZA
		{
			get
			{
				return this._MAESOC_ACTUALIZA;
			}
			set
			{
				if ((this._MAESOC_ACTUALIZA != value))
				{
					this.OnMAESOC_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_ACTUALIZA = value;
					this.SendPropertyChanged("MAESOC_ACTUALIZA");
					this.OnMAESOC_ACTUALIZAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_DTOFARMACIA", DbType="Int")]
		public System.Nullable<int> MAESOC_DTOFARMACIA
		{
			get
			{
				return this._MAESOC_DTOFARMACIA;
			}
			set
			{
				if ((this._MAESOC_DTOFARMACIA != value))
				{
					this.OnMAESOC_DTOFARMACIAChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_DTOFARMACIA = value;
					this.SendPropertyChanged("MAESOC_DTOFARMACIA");
					this.OnMAESOC_DTOFARMACIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_FECHAALTA", DbType="Date NOT NULL")]
		public System.DateTime MAESOC_FECHAALTA
		{
			get
			{
				return this._MAESOC_FECHAALTA;
			}
			set
			{
				if ((this._MAESOC_FECHAALTA != value))
				{
					this.OnMAESOC_FECHAALTAChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_FECHAALTA = value;
					this.SendPropertyChanged("MAESOC_FECHAALTA");
					this.OnMAESOC_FECHAALTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_FECHAMOD", DbType="Date NOT NULL")]
		public System.DateTime MAESOC_FECHAMOD
		{
			get
			{
				return this._MAESOC_FECHAMOD;
			}
			set
			{
				if ((this._MAESOC_FECHAMOD != value))
				{
					this.OnMAESOC_FECHAMODChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_FECHAMOD = value;
					this.SendPropertyChanged("MAESOC_FECHAMOD");
					this.OnMAESOC_FECHAMODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESOC_USUMOD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAESOC_USUMOD
		{
			get
			{
				return this._MAESOC_USUMOD;
			}
			set
			{
				if ((this._MAESOC_USUMOD != value))
				{
					this.OnMAESOC_USUMODChanging(value);
					this.SendPropertyChanging();
					this._MAESOC_USUMOD = value;
					this.SendPropertyChanged("MAESOC_USUMOD");
					this.OnMAESOC_USUMODChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fotos_.soccen_1")]
	public partial class soccen_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _SOCCEN_CUIL;
		
		private byte _SOCCEN_ESTADO;
		
		private int _SOCCEN_CODIVA;
		
		private System.Nullable<System.DateTime> _SOCCEN_FEING;
		
		private System.Nullable<System.DateTime> _SOCCEN_FEBAJA;
		
		private int _SOCCEN_NRORESCOMDIR;
		
		private long _SOCCEN_CREDMAX;
		
		private char _SOCCEN_CONDCRED;
		
		private byte _SOCCEN_SOCDIR;
		
		private byte _SOCCEN_DESPEDIDO;
		
		private System.Nullable<byte> _SOCCEN_ACTUALIZA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOCCEN_CUILChanging(double value);
    partial void OnSOCCEN_CUILChanged();
    partial void OnSOCCEN_ESTADOChanging(byte value);
    partial void OnSOCCEN_ESTADOChanged();
    partial void OnSOCCEN_CODIVAChanging(int value);
    partial void OnSOCCEN_CODIVAChanged();
    partial void OnSOCCEN_FEINGChanging(System.Nullable<System.DateTime> value);
    partial void OnSOCCEN_FEINGChanged();
    partial void OnSOCCEN_FEBAJAChanging(System.Nullable<System.DateTime> value);
    partial void OnSOCCEN_FEBAJAChanged();
    partial void OnSOCCEN_NRORESCOMDIRChanging(int value);
    partial void OnSOCCEN_NRORESCOMDIRChanged();
    partial void OnSOCCEN_CREDMAXChanging(long value);
    partial void OnSOCCEN_CREDMAXChanged();
    partial void OnSOCCEN_CONDCREDChanging(char value);
    partial void OnSOCCEN_CONDCREDChanged();
    partial void OnSOCCEN_SOCDIRChanging(byte value);
    partial void OnSOCCEN_SOCDIRChanged();
    partial void OnSOCCEN_DESPEDIDOChanging(byte value);
    partial void OnSOCCEN_DESPEDIDOChanged();
    partial void OnSOCCEN_ACTUALIZAChanging(System.Nullable<byte> value);
    partial void OnSOCCEN_ACTUALIZAChanged();
    #endregion
		
		public soccen_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_CUIL", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double SOCCEN_CUIL
		{
			get
			{
				return this._SOCCEN_CUIL;
			}
			set
			{
				if ((this._SOCCEN_CUIL != value))
				{
					this.OnSOCCEN_CUILChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_CUIL = value;
					this.SendPropertyChanged("SOCCEN_CUIL");
					this.OnSOCCEN_CUILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_ESTADO", DbType="TinyInt NOT NULL")]
		public byte SOCCEN_ESTADO
		{
			get
			{
				return this._SOCCEN_ESTADO;
			}
			set
			{
				if ((this._SOCCEN_ESTADO != value))
				{
					this.OnSOCCEN_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_ESTADO = value;
					this.SendPropertyChanged("SOCCEN_ESTADO");
					this.OnSOCCEN_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_CODIVA", DbType="Int NOT NULL")]
		public int SOCCEN_CODIVA
		{
			get
			{
				return this._SOCCEN_CODIVA;
			}
			set
			{
				if ((this._SOCCEN_CODIVA != value))
				{
					this.OnSOCCEN_CODIVAChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_CODIVA = value;
					this.SendPropertyChanged("SOCCEN_CODIVA");
					this.OnSOCCEN_CODIVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_FEING", DbType="Date")]
		public System.Nullable<System.DateTime> SOCCEN_FEING
		{
			get
			{
				return this._SOCCEN_FEING;
			}
			set
			{
				if ((this._SOCCEN_FEING != value))
				{
					this.OnSOCCEN_FEINGChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_FEING = value;
					this.SendPropertyChanged("SOCCEN_FEING");
					this.OnSOCCEN_FEINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_FEBAJA", DbType="Date")]
		public System.Nullable<System.DateTime> SOCCEN_FEBAJA
		{
			get
			{
				return this._SOCCEN_FEBAJA;
			}
			set
			{
				if ((this._SOCCEN_FEBAJA != value))
				{
					this.OnSOCCEN_FEBAJAChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_FEBAJA = value;
					this.SendPropertyChanged("SOCCEN_FEBAJA");
					this.OnSOCCEN_FEBAJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_NRORESCOMDIR", DbType="Int NOT NULL")]
		public int SOCCEN_NRORESCOMDIR
		{
			get
			{
				return this._SOCCEN_NRORESCOMDIR;
			}
			set
			{
				if ((this._SOCCEN_NRORESCOMDIR != value))
				{
					this.OnSOCCEN_NRORESCOMDIRChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_NRORESCOMDIR = value;
					this.SendPropertyChanged("SOCCEN_NRORESCOMDIR");
					this.OnSOCCEN_NRORESCOMDIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_CREDMAX", DbType="BigInt NOT NULL")]
		public long SOCCEN_CREDMAX
		{
			get
			{
				return this._SOCCEN_CREDMAX;
			}
			set
			{
				if ((this._SOCCEN_CREDMAX != value))
				{
					this.OnSOCCEN_CREDMAXChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_CREDMAX = value;
					this.SendPropertyChanged("SOCCEN_CREDMAX");
					this.OnSOCCEN_CREDMAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_CONDCRED", DbType="Char(1) NOT NULL")]
		public char SOCCEN_CONDCRED
		{
			get
			{
				return this._SOCCEN_CONDCRED;
			}
			set
			{
				if ((this._SOCCEN_CONDCRED != value))
				{
					this.OnSOCCEN_CONDCREDChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_CONDCRED = value;
					this.SendPropertyChanged("SOCCEN_CONDCRED");
					this.OnSOCCEN_CONDCREDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_SOCDIR", DbType="TinyInt NOT NULL")]
		public byte SOCCEN_SOCDIR
		{
			get
			{
				return this._SOCCEN_SOCDIR;
			}
			set
			{
				if ((this._SOCCEN_SOCDIR != value))
				{
					this.OnSOCCEN_SOCDIRChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_SOCDIR = value;
					this.SendPropertyChanged("SOCCEN_SOCDIR");
					this.OnSOCCEN_SOCDIRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_DESPEDIDO", DbType="TinyInt NOT NULL")]
		public byte SOCCEN_DESPEDIDO
		{
			get
			{
				return this._SOCCEN_DESPEDIDO;
			}
			set
			{
				if ((this._SOCCEN_DESPEDIDO != value))
				{
					this.OnSOCCEN_DESPEDIDOChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_DESPEDIDO = value;
					this.SendPropertyChanged("SOCCEN_DESPEDIDO");
					this.OnSOCCEN_DESPEDIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCCEN_ACTUALIZA", DbType="TinyInt")]
		public System.Nullable<byte> SOCCEN_ACTUALIZA
		{
			get
			{
				return this._SOCCEN_ACTUALIZA;
			}
			set
			{
				if ((this._SOCCEN_ACTUALIZA != value))
				{
					this.OnSOCCEN_ACTUALIZAChanging(value);
					this.SendPropertyChanging();
					this._SOCCEN_ACTUALIZA = value;
					this.SendPropertyChanged("SOCCEN_ACTUALIZA");
					this.OnSOCCEN_ACTUALIZAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fotos_.socemp_1")]
	public partial class socemp_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _SOCEMP_CUIL;
		
		private double _SOCEMP_CUITE;
		
		private byte _SOCEMP_ESTADO;
		
		private System.DateTime _SOCEMP_FECHAING;
		
		private System.DateTime _SOCEMP_FECHABAJA;
		
		private char _SOCEMP_CAUSABAJA;
		
		private string _SOCEMP_NROLEG;
		
		private byte _SOCEMP_SOCIOCENTRO;
		
		private char _SOCEMP_ULT_EMPRESA;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOCEMP_CUILChanging(double value);
    partial void OnSOCEMP_CUILChanged();
    partial void OnSOCEMP_CUITEChanging(double value);
    partial void OnSOCEMP_CUITEChanged();
    partial void OnSOCEMP_ESTADOChanging(byte value);
    partial void OnSOCEMP_ESTADOChanged();
    partial void OnSOCEMP_FECHAINGChanging(System.DateTime value);
    partial void OnSOCEMP_FECHAINGChanged();
    partial void OnSOCEMP_FECHABAJAChanging(System.DateTime value);
    partial void OnSOCEMP_FECHABAJAChanged();
    partial void OnSOCEMP_CAUSABAJAChanging(char value);
    partial void OnSOCEMP_CAUSABAJAChanged();
    partial void OnSOCEMP_NROLEGChanging(string value);
    partial void OnSOCEMP_NROLEGChanged();
    partial void OnSOCEMP_SOCIOCENTROChanging(byte value);
    partial void OnSOCEMP_SOCIOCENTROChanged();
    partial void OnSOCEMP_ULT_EMPRESAChanging(char value);
    partial void OnSOCEMP_ULT_EMPRESAChanged();
    #endregion
		
		public socemp_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_CUIL", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double SOCEMP_CUIL
		{
			get
			{
				return this._SOCEMP_CUIL;
			}
			set
			{
				if ((this._SOCEMP_CUIL != value))
				{
					this.OnSOCEMP_CUILChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_CUIL = value;
					this.SendPropertyChanged("SOCEMP_CUIL");
					this.OnSOCEMP_CUILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_CUITE", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double SOCEMP_CUITE
		{
			get
			{
				return this._SOCEMP_CUITE;
			}
			set
			{
				if ((this._SOCEMP_CUITE != value))
				{
					this.OnSOCEMP_CUITEChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_CUITE = value;
					this.SendPropertyChanged("SOCEMP_CUITE");
					this.OnSOCEMP_CUITEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_ESTADO", DbType="TinyInt NOT NULL")]
		public byte SOCEMP_ESTADO
		{
			get
			{
				return this._SOCEMP_ESTADO;
			}
			set
			{
				if ((this._SOCEMP_ESTADO != value))
				{
					this.OnSOCEMP_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_ESTADO = value;
					this.SendPropertyChanged("SOCEMP_ESTADO");
					this.OnSOCEMP_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_FECHAING", DbType="Date NOT NULL")]
		public System.DateTime SOCEMP_FECHAING
		{
			get
			{
				return this._SOCEMP_FECHAING;
			}
			set
			{
				if ((this._SOCEMP_FECHAING != value))
				{
					this.OnSOCEMP_FECHAINGChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_FECHAING = value;
					this.SendPropertyChanged("SOCEMP_FECHAING");
					this.OnSOCEMP_FECHAINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_FECHABAJA", DbType="Date NOT NULL")]
		public System.DateTime SOCEMP_FECHABAJA
		{
			get
			{
				return this._SOCEMP_FECHABAJA;
			}
			set
			{
				if ((this._SOCEMP_FECHABAJA != value))
				{
					this.OnSOCEMP_FECHABAJAChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_FECHABAJA = value;
					this.SendPropertyChanged("SOCEMP_FECHABAJA");
					this.OnSOCEMP_FECHABAJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_CAUSABAJA", DbType="Char(1) NOT NULL")]
		public char SOCEMP_CAUSABAJA
		{
			get
			{
				return this._SOCEMP_CAUSABAJA;
			}
			set
			{
				if ((this._SOCEMP_CAUSABAJA != value))
				{
					this.OnSOCEMP_CAUSABAJAChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_CAUSABAJA = value;
					this.SendPropertyChanged("SOCEMP_CAUSABAJA");
					this.OnSOCEMP_CAUSABAJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_NROLEG", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string SOCEMP_NROLEG
		{
			get
			{
				return this._SOCEMP_NROLEG;
			}
			set
			{
				if ((this._SOCEMP_NROLEG != value))
				{
					this.OnSOCEMP_NROLEGChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_NROLEG = value;
					this.SendPropertyChanged("SOCEMP_NROLEG");
					this.OnSOCEMP_NROLEGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_SOCIOCENTRO", DbType="TinyInt NOT NULL")]
		public byte SOCEMP_SOCIOCENTRO
		{
			get
			{
				return this._SOCEMP_SOCIOCENTRO;
			}
			set
			{
				if ((this._SOCEMP_SOCIOCENTRO != value))
				{
					this.OnSOCEMP_SOCIOCENTROChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_SOCIOCENTRO = value;
					this.SendPropertyChanged("SOCEMP_SOCIOCENTRO");
					this.OnSOCEMP_SOCIOCENTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCEMP_ULT_EMPRESA", DbType="Char(1) NOT NULL")]
		public char SOCEMP_ULT_EMPRESA
		{
			get
			{
				return this._SOCEMP_ULT_EMPRESA;
			}
			set
			{
				if ((this._SOCEMP_ULT_EMPRESA != value))
				{
					this.OnSOCEMP_ULT_EMPRESAChanging(value);
					this.SendPropertyChanging();
					this._SOCEMP_ULT_EMPRESA = value;
					this.SendPropertyChanged("SOCEMP_ULT_EMPRESA");
					this.OnSOCEMP_ULT_EMPRESAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fotos_.socflia_1")]
	public partial class socflia_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _SOCFLIA_CUIL;
		
		private long _SOCFLIA_CODFLIAR;
		
		private byte _SOCFLIA_ESTADO;
		
		private int _SOCFLIA_PARENT;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOCFLIA_CUILChanging(double value);
    partial void OnSOCFLIA_CUILChanged();
    partial void OnSOCFLIA_CODFLIARChanging(long value);
    partial void OnSOCFLIA_CODFLIARChanged();
    partial void OnSOCFLIA_ESTADOChanging(byte value);
    partial void OnSOCFLIA_ESTADOChanged();
    partial void OnSOCFLIA_PARENTChanging(int value);
    partial void OnSOCFLIA_PARENTChanged();
    #endregion
		
		public socflia_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCFLIA_CUIL", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double SOCFLIA_CUIL
		{
			get
			{
				return this._SOCFLIA_CUIL;
			}
			set
			{
				if ((this._SOCFLIA_CUIL != value))
				{
					this.OnSOCFLIA_CUILChanging(value);
					this.SendPropertyChanging();
					this._SOCFLIA_CUIL = value;
					this.SendPropertyChanged("SOCFLIA_CUIL");
					this.OnSOCFLIA_CUILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCFLIA_CODFLIAR", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long SOCFLIA_CODFLIAR
		{
			get
			{
				return this._SOCFLIA_CODFLIAR;
			}
			set
			{
				if ((this._SOCFLIA_CODFLIAR != value))
				{
					this.OnSOCFLIA_CODFLIARChanging(value);
					this.SendPropertyChanging();
					this._SOCFLIA_CODFLIAR = value;
					this.SendPropertyChanged("SOCFLIA_CODFLIAR");
					this.OnSOCFLIA_CODFLIARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCFLIA_ESTADO", DbType="TinyInt NOT NULL")]
		public byte SOCFLIA_ESTADO
		{
			get
			{
				return this._SOCFLIA_ESTADO;
			}
			set
			{
				if ((this._SOCFLIA_ESTADO != value))
				{
					this.OnSOCFLIA_ESTADOChanging(value);
					this.SendPropertyChanging();
					this._SOCFLIA_ESTADO = value;
					this.SendPropertyChanged("SOCFLIA_ESTADO");
					this.OnSOCFLIA_ESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOCFLIA_PARENT", DbType="Int NOT NULL")]
		public int SOCFLIA_PARENT
		{
			get
			{
				return this._SOCFLIA_PARENT;
			}
			set
			{
				if ((this._SOCFLIA_PARENT != value))
				{
					this.OnSOCFLIA_PARENTChanging(value);
					this.SendPropertyChanging();
					this._SOCFLIA_PARENT = value;
					this.SendPropertyChanged("SOCFLIA_PARENT");
					this.OnSOCFLIA_PARENTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
